Repository Galaxia5987/robot-2022, pull requests merged in 2022-01, with the labels that each got.

#15 Simulate shooter
  src/main/java/frc/robot/Constants.java
Labels: simulation, subsystem, Priority: High

#41 Simulate vision
  simgui-ds.json
  simgui-window.json
  simgui.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/utils/PhotonVisionModule.java
  src/main/java/frc/robot/utils/SimulateDrivetrain.java
  src/main/java/frc/robot/utils/VisionEstimationData.java
  src/main/java/frc/robot/utils/commands/SimulateDrivetrainDefaultCommand.java
  vendordeps/PhotonLib-json-1.0.json
Labels: simulation, Priority: High, vision

#23 Simulate climber
  build.gradle
  simgui-ds.json
  simgui-window.json
  simgui.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Main.java
  src/main/java/frc/robot/Ports.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/climber/Climber.java
  src/main/java/frc/robot/subsystems/climber/commands/ClimberStop.java
  src/main/java/frc/robot/subsystems/climber/commands/JoystickClimb.java
Labels: simulation, Priority: Medium, unit test

#16 Climber
  simgui-window.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Main.java
  src/main/java/frc/robot/Ports.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/UnitModel.java
  src/main/java/frc/robot/subsystems/climber/Climber.java
  src/main/java/frc/robot/subsystems/climber/commands/ClimberStop.java
  src/main/java/frc/robot/subsystems/climber/commands/JoystickClimb.java
  src/main/java/frc/robot/utils/PhotonVisionModule.java
  src/main/java/frc/robot/utils/SimulateDrivetrain.java
Labels: subsystem, Priority: Critical

#21 Value Tuner 2
  build.gradle
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Main.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/valuetuner/ConstantObject.java
  src/main/java/frc/robot/valuetuner/NetworkTableConstant.java
  src/main/java/frc/robot/valuetuner/TalonConstant.java
  src/main/java/frc/robot/valuetuner/ValueTuner.java
  src/main/java/frc/robot/valuetuner/WebConstant.java
  src/main/java/frc/robot/valuetuner/WebConstantPIDTalon.java
  src/main/java/frc/robot/valuetuner/WrapperConstant.java
  src/main/resources/tuner.vm
Labels: enhancement, Priority: Medium, tuning

#33 Simulate shooter
  simgui-window.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command_groups/Outtake.java
  src/main/java/frc/robot/subsystems/shooter/Shooter.java
  src/main/java/frc/robot/subsystems/shooter/commands/Shoot.java
  src/main/java/frc/robot/subsystems/shooter/commands/bits/TestPistonPressure.java
  src/main/java/frc/robot/utils/Utils.java
Labels: simulation, Priority: High

#27 Hood
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Ports.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/hood/Hood.java
Labels: subsystem, Priority: Critical

#54 Update gitignore
  .gitignore
  .idea/.gitignore
  simgui-ds.json
  simgui-window.json
  simgui.json
Labels: Priority: Low, cleanup
